# render.yaml
databases:
  - name: laravel-transaction-db
    databaseName: laravel_transaction_api
    user: laravel_user
    plan: free

services:
  # Main Web Application
  - type: web
    name: laravel-transaction-api
    runtime: php
    plan: free
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    healthCheckPath: "/api/v1/health"
    envVars:
      - key: APP_NAME
        value: "Laravel Transaction API"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://laravel-transaction-api.onrender.com
      - key: LOG_CHANNEL
        value: errorlog
      - key: LOG_LEVEL
        value: error
      - key: LOG_DEPRECATIONS_CHANNEL
        value: "null"

      # Database Configuration
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: laravel-transaction-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: laravel-transaction-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: laravel-transaction-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: laravel-transaction-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: laravel-transaction-db
          property: password

      # Application Configuration
      - key: BROADCAST_DRIVER
        value: log
      - key: CACHE_DRIVER
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: database
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: "120"

      # Mail Configuration
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: mailpit
      - key: MAIL_PORT
        value: "1025"
      - key: MAIL_USERNAME
        value: "null"
      - key: MAIL_PASSWORD
        value: "null"
      - key: MAIL_ENCRYPTION
        value: "null"
      - key: MAIL_FROM_ADDRESS
        value: "hello@example.com"
      - key: MAIL_FROM_NAME
        value: "Laravel Transaction API"

  # Background Queue Worker
  - type: worker
    name: laravel-queue-worker
    runtime: php
    plan: free
    buildCommand: "./build.sh"
    startCommand: "php artisan queue:work --verbose --tries=3 --timeout=90 --sleep=3 --max-time=3600"
    envVars:
      - key: APP_NAME
        value: "Laravel Transaction API"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: LOG_CHANNEL
        value: errorlog
      - key: LOG_LEVEL
        value: error

      # Database Configuration (same as web service)
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: laravel-transaction-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: laravel-transaction-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: laravel-transaction-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: laravel-transaction-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: laravel-transaction-db
          property: password

      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_DRIVER
        value: file
