# render.yaml
databases:
  - name: laravel-transaction-db
    databaseName: laravel_transaction_api
    user: laravel_user
    plan: free

services:
  - type: web
    name: laravel-transaction-api
    runtime: docker
    plan: free
    healthCheckPath: "/api/v1/health"
    envVars:
      # Laravel Configuration
      - key: APP_NAME
        value: "Laravel Transaction API"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://laravel-transaction-api.onrender.com

      # Logging
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_DEPRECATIONS_CHANNEL
        value: "null"
      - key: LOG_LEVEL
        value: info

      # Database Configuration
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: laravel-transaction-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: laravel-transaction-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: laravel-transaction-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: laravel-transaction-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: laravel-transaction-db
          property: password

      # Laravel Services
      - key: BROADCAST_DRIVER
        value: log
      - key: CACHE_DRIVER
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: database
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: "120"

      # Security
      - key: SANCTUM_STATEFUL_DOMAINS
        value: "localhost,localhost:3000,127.0.0.1,127.0.0.1:8000,::1"

      # Mail Configuration
      - key: MAIL_MAILER
        value: log
      - key: MAIL_HOST
        value: smtp.mailtrap.io
      - key: MAIL_PORT
        value: "2525"
      - key: MAIL_USERNAME
        value: "null"
      - key: MAIL_PASSWORD
        value: "null"
      - key: MAIL_ENCRYPTION
        value: "null"
      - key: MAIL_FROM_ADDRESS
        value: "noreply@laravel-transaction-api.com"
      - key: MAIL_FROM_NAME
        value: "Laravel Transaction API"
